version: 66.66.66.{build}

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
skip_tags: true

# set clone depth
clone_depth: 1                     # clone entire repository history if not defined

branches:
  only:
  - /experimental\/*/

matrix:
  fast_finish: false

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2019

environment:
  # The following entries define the default values of the environment variables.
  # They can be overridden in AppVeyor | Settings | Environment.
  GE_TEST_SLEEP_SECONDS_ON_HANG: 0
  GE_TEST_LAUNCH_DEBUGGER_ON_HANG: 0
  # How many times to execute tests
  TEST_RUN_COUNT: 1
  # Execute unit tests
  RUN_UNIT_TESTS: 1
  # Execute integation tests
  RUN_INTEGRATION_TESTS: 1
  # Fail the build if any of the tests fail
  FAIL_BUILD_IF_TESTS_FAIL: 1

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  # enable MSBuild parallel builds
  parallel: true
  # MSBuild verbosity level
  verbosity: minimal

install:
- cmd: git submodule update --init --recursive
- cmd: echo /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll">> Directory.Build.rsp
- cmd: |-
    cd scripts
    C:\\Python35\\python set_version_to.py -v %APPVEYOR_BUILD_VERSION% -t %APPVEYOR_BUILD_VERSION%
    cd ..


# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: |
    # for release branches mark the repo as clean
    if (!$env:APPVEYOR_PULL_REQUEST_TITLE -and $env:APPVEYOR_REPO_BRANCH.StartsWith("release/")) {
      & .\scripts\Mark-RepoClean.ps1
    }

    # build
    & .\cibuild.cmd -restore -build -buildNative
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }


# to run your custom scripts instead of automatic tests
test_script:
- ps: |
    $failBuildIfTestsFail = $env:FAIL_BUILD_IF_TESTS_FAIL
    $runUnitTests         = $env:RUN_UNIT_TESTS
    $runIntegrationTests  = $env:RUN_INTEGRATION_TESTS
    $testRunCount         = $env:TEST_RUN_COUNT

    Write-Host "FAIL_BUILD_IF_TESTS_FAIL:        ${failBuildIfTestsFail}"
    Write-Host "RUN_UNIT_TESTS:                  ${runUnitTests}"
    Write-Host "RUN_INTEGRATION_TESTS:           ${runIntegrationTests}"
    Write-Host "TEST_RUN_COUNT:                  ${testRunCount}"
    Write-Host "GE_TEST_SLEEP_SECONDS_ON_HANG:   ${env:GE_TEST_SLEEP_SECONDS_ON_HANG}"
    Write-Host "GE_TEST_LAUNCH_DEBUGGER_ON_HANG: ${env:GE_TEST_LAUNCH_DEBUGGER_ON_HANG}"

    $testErrorsTotal = 0
    for ($testRun = 1; $testRun -le $testRunCount; $testRun++)
    {
        $failedBefore = if ($testRun -ne 1) { ", ${testErrorsTotal} test(s) failed before" }
        Write-Host ""
        Write-Host "[INFO]: Test Run ${testRun}/${testRunCount}${failedBefore}"

        if ($runUnitTests        -ne 0) { & .\cibuild.cmd -test }
        if ($runIntegrationTests -ne 0) { & .\cibuild.cmd -integrationTest }

        Get-ChildItem -recurse artifacts\tests\TestResult.xml -ErrorAction SilentlyContinue `
        | ForEach-Object {
            $resultFilePath = "$_"
            Get-Content $resultFilePath `
            | Select-String -Pattern '<test-run id="[^"]*"\s+testcasecount="(\d+)"\s+result="([^"]*)"\s+total="(\d+)"\s+passed="(\d+)"\s+failed="(\d+)".*' `
            | foreach {
                $result = $_.Matches.Groups
                #$result[0].Value
                $total  = $result[1].Value
                $passed = $result[4].Value
                $failed = $result[5].Value
                $notPassed = $total - $passed
                $testErrors = $failed
                $testProjectName = $resultFilePath.Split('\\')[-3]
                $artifactName = "TestResult#${testRun}.${testErrors}err.${testProjectName}"
                Push-AppveyorArtifact $resultFilePath -FileName "${artifactName}.xml"
                if ($notPassed -ne 0) {
                    $logFile = Get-ChildItem -recurse artifacts\$testProjectName*.log
                    if ($testErrors -ne 0) { Push-AppveyorArtifact $logFile -FileName "${artifactName}.log" }
                }
                $testErrorsTotal += $testErrors
            }
        }
    }
    if ($testErrorsTotal -ne 0  -and  $failBuildIfTestsFail -ne 0) { $host.SetShouldExit($testErrorsTotal) }


# scripts to run after tests
after_test:
- ps: |
    Write-Host "Preparing build artifacts..."
    & .\cibuild.cmd -publish
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }


artifacts:
  - path: artifacts\log\**\*.binlog
  - path: artifacts\publish\*.zip

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
